Fixed unexpected deletion of log files of other processes that led to OSError: [Errno 116] Stale file handle error on NFS volumes (#8121)
Due the nocleanup option defaults to false and we use AUTO-generated
names for backend process log files, this causes NFS4ERR_STALE to appear
on NFS-mounted volumes
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 109, in emit
    self.flush()
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 68, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
```

http://supervisord.org/configuration.html#:~:text=Introduced%3A%203.0-,nocleanup,-Prevent%20supervisord%20from

https://stackoverflow.com/questions/40262823/stale-file-handle-error-when-process-trying-read-the-file-that-other-process

Co-authored-by: Roman Donchenko <roman@cvat.ai>